[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rental_escrow = "BiwaGavQUsSsg48UPpRAGWoXSiUnzgvdDs7rd8WizvPD"

[provider]
cluster = "Localnet"
wallet = "/private/tmp/rental-solana-test-wallet.json"

[scripts]
test = "cargo test --workspace --features test-deployment"
